### ISSUE TITLE
No Access to data_recording

### ISSUE THREAD

**Issue by gjj0430** [flatironinstitute/spikeforest2#37]
I couldn't get the recording according to Readme. Is this project unavailable now?

**Comment by jsoules** [comment]
Hi, the project should still be available but we've been making some ongoing changes to the tool that distributes the files. Please let us know the exact steps you attempted and what happened and we'll look into how to get you the data. Thanks!

**Comment by jsoules** [comment]
Hi again,

I apologize--I answered too quickly here. This project is no longer maintained; you should be looking at the Spikeforest project instead (https://github.com/flatironinstitute/spikeforest -- yes, spikeforest is more recent than spikeforest2, as confusing as that may be!) Though again, you may encounter some difficulty due to changes in the back-end that's being used to store the data.

Please have a look at that project and feel free to reach out with a further issue there if you are still unable to retrieve the data you need.

**Comment by gjj0430** [comment]
I appreciate it greatly! Thank you, sir.
